### ISSUE TITLE
No available balance on sell order

### ISSUE THREAD

**Issue by sebamatusr** [thebotguys/cryptopia-api-python#17]
I get the following error when trying to place a live sell order using python 3:

Traceback (most recent call last):
  File "C:/pump-dump.py", line 142, in <module>
    COINS_OWNED, ERROR = API.get_balance(PUMP_COIN)[0]['Available']
TypeError: 'float' object is not iterable

**Comment by jimmus217** [comment]
I'm seeing this too.  I'm not a Python dev but I'm thinking of trying to modify this so the sell order price is based on order filled price rather than the PUMP_SELL price.

**Comment by sebamatusr** [comment]
I think it's because the API.get_balance returns a float (i.e 0.01234) and the program is trying to iterate through it as if it was an array (which is not) trying to find the 'Available Key'.

**Comment by saniales** [comment]
I will fix it on next update, whanks for the feedback
