### ISSUE TITLE
Can't process methods that use no argument

### ISSUE THREAD

**Issue by riv1986** [thebotguys/cryptopia-api-python#24]
So when I call a function that needs an argument such as get_balance('BTC') or get_market('LTC_BTC'), your module works perfectly, but when just request general information such as get_markets, get_currencies, etc I get the message shown in the attached picture when doing: 

QTY_BTC_CRYPTOPIA = API_CRYPTOPIA.get_balance('BTC')
trade_pairs = API_CRYPTOPIA.get_markets()
![error python cryptopia](https://user-images.githubusercontent.com/35031196/35461717-9948a34e-02ae-11e8-84ec-4232d3885ebc.png)

Do you know what the problem might be? Thanks!

**Comment by saniales** [comment]
Problem is because no parameter is provided so it auto initializes to none
Will fix tomorrow :+1:

**Comment by riv1986** [comment]
Thank you! I'm excited to have that part working
