### ISSUE TITLE
Buy Order placed at marketplace price

### ISSUE THREAD

**Issue by Fabiomoretti** [thebotguys/cryptopia-api-python#29]
I'm testing the script with a low qt. of BTC
I put an order to buy at 5% and sell at 15% a specific COIN.
On the Terminal I saw the correct 5%+ buy price  but in my Cryptopia accout my buy order was immediatly placed with 2 operations at market price (0.00011936 and 0.00011941) instead of 0.00012533 BTC

This is the terminal response:
-----------------------

Entry point acceptable!

Using 0.00813104 BTC to buy ORME .
Current ASK price for ORME is 0.00011936 BTC.

ASK + 5.0% (your specified buy point) for ORME is 0.00012533            BTC.
ASK + 15.0% (your specified sell point) for ORME is 0.00013726            BTC.

[+] Buy order placed for 64.74767498 ORME coins at 0.00012533 BTC            each for a total of 0.0081146966096 BTC
{u'OrderId': None, u'FilledOrders': [50561134, 50561135]}

[+] Placing sell order at 0.00013726 (+15.0%)...

[+] Sell order placed of 64.74767498 ORME coins at 0.00013726 BTC each for           a total of 0.00888752 BTC
[*] PROFIT if sell order fills: 0.00077283 BTC

-------------------------------

Why this error?
Many Thansk

**Comment by rAey** [comment]
This is not an issue with the bot, but rather how markets work. If you place a buy order 5% above the current Ask, your order will be instantly filled of course since you want to buy above current market price. The bot worked fine, your understanding of markets did not :)

**Comment by saniales** [comment]
Exactly, closing this issue :)
