### ISSUE TITLE
Get all balances at once??

### ISSUE THREAD

**Issue by 7013145** [thebotguys/cryptopia-api-python#36]
I am told everywhere that to get all my balances, and not query them one by one, i should send request with post parameter as {'Currency' : ''} or simply { } .. I have tried both ways and they work but only return my balance for $PAC for some reason.. I have BTC and ETH on my cryptopia account, and trading works so i have no clue why i can not return all my balances with GetBalance, no matter the post_parameters i pass..

Can anyone using this API implementation please tell me if you are able to retrieve all balances in 1 api call with the `GetBalance` call and `post_parameter={'Currency' : ''}`

This is working for someone i talked to, but is not working for me. He was using a PHP implementation though.

**Comment by 7013145** [comment]
Found the problem, and boy was it a facepalm moment :dagger: 
Unfortunately, im too noob to do a proper contribution with push/pull whatever, but PLEASE someone change `result = result[0]` to 'result = result' so that we can actually utilize all the data and not just the very first element. Remove that pointless if statement, that you see fit to place only in that function apparety so it looks like the other calls:

`result, error = self.api_query(feature_requested='GetBalance', post_parameters={'Currency': currency})`
`return (result, error)`

making all the data available, not just $PAC balance.

**Comment by saniales** [comment]
`get_balance` function is for a single currency only, we are planning to implement a `get_balances` function which does what you request. I am closing this and opening a feature request issue
