### ISSUE TITLE
Implement get_balances function

### ISSUE THREAD

**Issue by saniales** [thebotguys/cryptopia-api-python#37]
signature:
``` python
def get_balances():
    return list_of_all_balances_from_user, error_if_any
```

**Comment by 7013145** [comment]
It is simple as hell, and should take literally minutes.

Replace current `get_balances` function with below and voilá:
```
def get_balance(self, currency=''):
        result, error = self.api_query(feature_requested='GetBalance',
                                       post_parameters={'Currency': currency})
        if error:
            return error
        return (result, error)
```
Now you can do `get_balance()` to get all balances using default ` '' ` parameter. If user want single balance, `coin` parameter is simply passed as before. If user (for whatever reason) wanna have the functionality you force upon them now, they simply call `get_balance()[0]` to get very first currency returned.

I am itching to make a pull request for this, but frankly, the task of figuring out how is daunting at the moment. Besides, I made the fix in my own code so screw you guys, im going home.. :)

**Comment by saniales** [comment]
@7013145 open source is love, you do not love us :P

**Comment by 7013145** [comment]
@saniales Yes, if 'Currency' post parameter is left empty the GetBalance method returns the full balance list, rather than a single currency.

**Comment by letbotsdothework** [comment]
Sorry, I'm new to this all. Say, I want to check my BTC balance. How would I implement this parameter into the GetBalance methode?

**Comment by saniales** [comment]
just call get_balance('BTC'), I am closing this issue, you can reopen another one since the "coding issue" has been solved

**Comment by 7013145** [comment]
see pull request: https://github.com/thebotguys/cryptopia-api-python/pull/40
