### ISSUE TITLE
Returns (None, 'Status Code : 401 Client Error: Unauthorized for url: https://www.cryptopia.co.nz/Api/GetBalance')

### ISSUE THREAD

**Issue by highmountainwarrior** [thebotguys/cryptopia-api-python#41]
Hi, I am getting an unauthorised error for all Private calls. Like get_balance(), get_opnorders().
I have made sure that I am using the right combination of api_key and secret. But still this error persists. Any suggestions?

I am calling the method as:
`api = Api(api_key, api_secret)
balances = api.get_balance("BTC")`

**Comment by saniales** [comment]
are u sure your private public keypair is correct? do you have correct permissions set for your api key?

**Comment by highmountainwarrior** [comment]
> are u sure your private public keypair is correct? do you have correct permissions set for your api key?

Yes. I checked. My keys are correct ones and I have required permissions on the API key. And I am using the latest version of the cryptopia_api.py. If that helps. Let me know if you need any additional details

**Comment by highmountainwarrior** [comment]
Did cryptopia change their request format recently?
